# Generated by Django 5.2 on 2025-05-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='room_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
