# Generated by Django 4.2.5 on 2025-11-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_property_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance')], default='rent', max_length=20),
        ),
    ]
