# Generated by Django 4.2.5 on 2025-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
